# Generated by Django 2.2.1 on 2019-05-04 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0002_billtags'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BillTags',
            new_name='BillTag',
        ),
    ]
