# Generated by Django 2.2.1 on 2019-05-04 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0007_auto_20190504_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='tags',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bills.BillTag'),
        ),
    ]
