# Generated by Django 2.2.1 on 2019-05-04 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0008_bill_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='tags',
        ),
        migrations.AddField(
            model_name='bill',
            name='tags',
            field=models.ManyToManyField(related_name='photos', to='bills.BillTag'),
        ),
    ]
