# Generated by Django 2.2.1 on 2019-05-04 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0009_auto_20190504_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='remainder_date',
            field=models.DateField(null=True),
        ),
    ]
