# Generated by Django 2.2.1 on 2019-05-04 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0010_bill_remainder_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='remainder_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
