# Generated by Django 2.2.1 on 2019-05-03 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_name', models.CharField(max_length=200)),
                ('town', models.CharField(max_length=200)),
                ('district', models.CharField(max_length=200)),
                ('pin_code', models.PositiveIntegerField()),
                ('created_on', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
